### PR TITLE
Multiple fixes

### PR DESCRIPTION
**Pull request by VladimirAmiorkov**
## PR Checklist

- [X] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [X] All existing tests are passing
- [ ] Tests for the changes are included

Fixes/Implements/Closes #[Issue Number].
https://github.com/NativeScript/nativescript-picker/issues/21
https://github.com/NativeScript/nativescript-picker/issues/22

### CODE REVIEW

**Comment by topclaudy** [comment]
Do you plan to add a 'valueSelected' event? Or can you provide the Vue version of the snippet you provide here https://github.com/NativeScript/nativescript-picker/issues/16 as a workaround?

```
export function pageLoaded(args: observable.EventData) {
    let page = <pages.Page>args.object;
    page.bindingContext = new GettingStartedModel();
    const picker = page.getViewById("myPicker");
    picker.on("textChange", onTextChange);
}

```

**Comment by VladimirAmiorkov** [comment]
Hi @topclaudy ,

At the moment no issues of this repository has been added to our planned tasks. The feature request is with very low priority and we could use a community PR for it if you are up to the task. Regarding an Vue snippet it depends on the way you are using `nativescript-vue` (.ts files or .vue files), but the idea of the workaround is to simply attach to the `Picker`'s `textChange` event. You can do that inside the `loaded` event of the `Page` or inside the `loaded` event of the `Picker` itself. Simply add an event handled in the methods of your Vue component where the Picker is used and use the above snippet (`picker.on("textChange", onTextChange);` and add a `onTextChange` handled to the methods also.

**Comment by topclaudy** [comment]
Hello @VladimirAmiorkov I tried this before asking the question. My first attempt was on the @loaded event of the page element. But for some reason it crashes when I call `picker.on(...)`. I tried the @loaded event on the picker element but it never fired.

**Comment by VladimirAmiorkov** [comment]
My mistake the `loaded` is broken in the latest version and is going to resolved with this PR. Regarding the crash when using the loaded of the Page is there an exception written in the terminal when the app crashes, can you share that with me? Also please write in [that issue](https://github.com/NativeScript/nativescript-picker/issues/16) rather than here because this PR is not related to that functionality.

**Review by tgpetrov — APPROVED** [review]

**Comment by zzhenryquezz** [comment]
> Do you plan to add a 'valueSelected' event? Or can you provide the Vue version of the snippet you provide here #16 as a workaround?
> 
> ```
> export function pageLoaded(args: observable.EventData) {
>     let page = <pages.Page>args.object;
>     page.bindingContext = new GettingStartedModel();
>     const picker = page.getViewById("myPicker");
>     picker.on("textChange", onTextChange);
> }
> ```

This is a way of workaround the issue in nativescript-vue:

Template:
```
<PickerField
     ref="picker"  
     class="picker-field"
     hint="Select an item"
     textField="name"
     for="item in items">
<PickerField/>
```
Javascript:
```
   mounted(){
        let picker = this.$refs.picker.nativeView;
        picker.on('textChange', this.onTextChange);
    },
```
I try put the @textChange event directly in the PickerField component but don't work, so I make this way.

**Comment by VladimirAmiorkov** [comment]
@zzhenryquezz Thank you, that is correct. The textChange event is in the NativeScript element rather than the VueJS component which is why @topclaudy was experiencing an exception.

**Pull request merged**
